### ISSUE TITLE
unresolved dependence 

### ISSUE THREAD

**Issue by urban48** [allegro/kafka-offset-monitor-graphite#4]
when trying to sbt publishM2 i get:
unresolved dependency: com.quantifind#kafkaoffsetmonitor_2.10;0.3.0-SNAPSHOT: not found

**Comment by adamdubiel** [comment]
Yes, we are aware that KafkaOffsetMonitor is not available in any public repo, so we added this in our docs:

"Currently **KafkaOffsetMonitor** is not available via public artifact repository, so before we build the plugin we **need to build KafkaOffsetMonitor and publish it to maven local** repo:"

:)

**Comment by urban48** [comment]
right, my bad. tnx!
