### ISSUE TITLE
names of metrics which create kafka-offset-monitor-graphite

### ISSUE THREAD

**Issue by unix196** [allegro/kafka-offset-monitor-graphite#5]
Good day.
I create issue in grafana project https://github.com/grafana/grafana/issues/13345  about that grafana cannot interpreter metrics with names `topic=ft-store` i.e. where character `=`. In that issue I receive answer that this character "=" doesn't support. So I decided write issue to you.
The following scheme is used:
* go-carbon 0.11.0 (implementation of the graphite server on Go)
* carbonapi  0.8.0  (carbonapi: replacement graphite API server) 
* brubeck (replacement statsd, write on C )
We using fork https://github.com/Morningstar/kafka-offset-monitor and https://github.com/wix-playground/kafka-offset-monitor-graphite because we need monitoring kafka offset lag through kafkaBrokers and view metrics in Grafana dashboard.
We run application with this command:
```
java -cp ./kafka-offset-monitor-graphite_2.10-0.1.0-SNAPSHOT-jar-with-dependencies.jar  com.quantifind.kafka.offsetapp.OffsetGetterWeb \
 --offsetStorage kafka --kafkaBrokers kafka-server:9092 \
 --zk zookeeper-server:2181/kafka --port 7080 --refresh 60.seconds --retain 1.days \
 --pluginsArgs graphiteHost=TEST,graphitePort=8125,graphitePrefix=kafka.prod,graphiteReportPeriod=30
```
In documentation need using graphite port 2003, but with him it didn't work. If I use statsd port (8125),  graphite server creates metrics with following names:
```
ls -l /graphite/whisper/stats/kafka/

drwxr-xr-x 4 graphite graphite 46 сен 19 08:01 topic=evs-action
drwxr-xr-x 3 graphite graphite 24 сен 19 08:00 topic=evs-counter
drwxr-xr-x 3 graphite graphite 24 сен 19 08:00 topic=evs-match
```

```
ls -l /graphite/whisper/stats/kafka/topic\=ft-store/group\=flumechannel-ft-store/partition\=0/
-rw-r--r-- 1 graphite graphite 585292 сен 19 13:54 gauge=lag_g.wsp
-rw-r--r-- 1 graphite graphite 585292 сен 19 13:53 gauge=logSize_g.wsp
-rw-r--r-- 1 graphite graphite 585292 сен 19 13:54 gauge=offset_g.wsp
```
Character `=` isn't good.  If I understand correctly, in your application metrics from kafka to graphite create with that character `=` also ? Maybe  use other delimiter? for example `-`

**Comment by rzukow** [comment]
As you are building this from source anyway, can you try to make a fix in method:

def getMetricName(offsetInfo: OffsetInfo): String = {
    offsetInfo.topic.replace(".", "_") + "." + offsetInfo.group.replace(".", "_") + "." + offsetInfo.partition
  }
https://github.com/allegro/kafka-offset-monitor-graphite/blob/master/src/main/scala/pl/allegro/tech/kafka/offset/monitor/graphite/OffsetGraphiteReporter.scala

where you can replace "=" the same way we we eliminate "." with anything you like (but supported by graphite), (maybe double _) and check if this solves your problem?

Maybe we should consider more general solution to be applied in the project though.

**Comment by unix196** [comment]
In fork 
https://github.com/wix-playground/kafka-offset-monitor-graphite/blob/master/src/main/scala/pl/allegro/tech/kafka/offset/monitor/graphite/OffsetGraphiteReporter.scala
use other string
```
def getMetricName(offsetInfo: OffsetInfo): String = {
    "topic=" + offsetInfo.topic.replace(".", "_") + ".group=" + offsetInfo.group.replace(".", "_") + ".partition=" + offsetInfo.partition + ".gauge="
}
```
Now I understood  what need change. Thanks!
